=== adamsilver/export-wins-ui-mi/src/data/schema/backend/os_regions/overview.schema.json
{
	"$schema": "http://json-schema.org/draft-04/schema#",
	"title": "Sector overview",

	"type": "array",
	"items": {
		"type": "object",
		"required": [ "hvc_performance", "id", "name", "markets", "confirmed_percent", "hvc_target_values" ],
		"properties": {
			"hvc_performance": {
				"$ref": "#/definitions/hvc-performance"
			},
			"id": {
				"type": "number",
				"faker": "random.number"
			},
			"name": {
				"type": "string",
				"faker": "lorem.words"
			},
			"markets": {
				"type": "number",
				"faker": {
					"random.number": [ 25 ]
				}
			},
			"confirmed_percent": {
				"type": "object",
				"required": [ "hvc", "non_hvc" ],
				"properties": {
					"hvc": {
						"type": "number",
						"faker": {
							"random.number": [ 100 ]
						}
					},
					"non_hvc": {
						"type": "number",
						"faker": {
							"random.number": [ 100 ]
						}
					}
				}
			},
			"hvc_target_values": {
				"$ref": "#/definitions/target-values"
			}
		}
	},
	"definitions": {
		"hvc-performance": {
			"type": "object",
			"required": [ "red", "amber", "green" ],
			"properties": {
				"red": {
					"type": "number",
					"faker": {
						"random.number": [ 25 ]
					}
				},
				"amber": {
					"type": "number",
					"faker": {
						"random.number": [ 25 ]
					}
				},
				"green": {
					"type": "number",
					"faker": {
						"random.number": [ 25 ]
					}
				}
			}
		},
		"target-values": {
			"type": "object",
			"required": [ "target_percentage", "current", "target" ],
			"properties": {
				"target_percentage": {
					"type": "number",
					"faker": {
						"random.number": [ 100 ]
					}
				},
				"current": {
					"type": "number",
					"faker": "random.number"
				},
				"target": {
					"type": "number",
					"chance": {
						"integer": { "min": 0 }
					}
				}
			}
		}
	}
}

=== adamsilver/export-wins-ui-mi/src/test/app/fake-data/backend/os_regions/overview.json
[
   {
      "hvc_performance": {
         "red": 12,
         "amber": 23,
         "green": 18
      },
      "id": 12164,
      "name": "tempora molestiae expedita",
      "markets": 2,
      "confirmed_percent": {
         "hvc": 83,
         "non_hvc": 17
      },
      "hvc_target_values": {
         "target_percentage": 77,
         "current": 79015,
         "target": 102617
      }
   },
   {
      "hvc_performance": {
         "red": 19,
         "amber": 10,
         "green": 2
      },
      "id": 25411,
      "name": "beatae omnis inventore",
      "markets": 17,
      "confirmed_percent": {
         "hvc": 100,
         "non_hvc": 0
      },
      "hvc_target_values": {
         "target_percentage": 79,
         "current": 36512,
         "target": 46218
      }
   },
   {
      "hvc_performance": {
         "red": 17,
         "amber": 7,
         "green": 8
      },
      "id": 18599,
      "name": "beatae et non",
      "markets": 2,
      "confirmed_percent": {
         "hvc": 77,
         "non_hvc": 23
      },
      "hvc_target_values": {
         "target_percentage": 31,
         "current": 67931,
         "target": 219132
      }
   },
   {
      "hvc_performance": {
         "red": 16,
         "amber": 22,
         "green": 2
      },
      "id": 15078,
      "name": "est sit aut",
      "markets": 10,
      "confirmed_percent": {
         "hvc": 89,
         "non_hvc": 11
      },
      "hvc_target_values": {
         "target_percentage": 95,
         "current": 34241,
         "target": 36043
      }
   },
   {
      "hvc_performance": {
         "red": 19,
         "amber": 4,
         "green": 23
      },
      "id": 63513,
      "name": "incidunt voluptatem nemo",
      "markets": 23,
      "confirmed_percent": {
         "hvc": 41,
         "non_hvc": 59
      },
      "hvc_target_values": {
         "target_percentage": 33,
         "current": 29381,
         "target": 89033
      }
   }
]
